/**
 * Application constants and configuration
 * Centralized configuration to avoid magic numbers throughout the codebase
 */

// Performance constants
export const PERFORMANCE = {
  FADE_STEPS: 24,
  FADE_MIN_MS: 16,
  STAR_COUNT: 420,
  TRAIL_CAP: 64,
  PUFF_SPAWN_INTERVAL: 0.032,
  JANK_DETECTION_FRAME_THRESHOLD: 32, // ms (~30fps)
  JANK_DETECTION_SAMPLE_SIZE: 120, // frames
  JANK_DETECTION_RATIO_THRESHOLD: 0.2, // 20% of frames janky
  JANK_RECOVERY_RATIO: 0.06, // recover if <6% janky
};

// Audio constants
export const AUDIO = {
  DEFAULT_SFX_VOLUME: 0.12,
  SHOOT_SFX_VOLUME: 0.22,
  BG_MUSIC_INITIAL_VOLUME: 0.15,
  BG_MUSIC_TARGET_VOLUME: 0.12,
  FADE_DURATION_MS: 1200,
};

// Starfield constants
export const STARFIELD = {
  IDLE_SPEED: 0.0,
  CRUISE_SPEED_NORMAL: 0.006,
  CRUISE_SPEED_REDUCED: 0.002,
  WARP_SPEED_NORMAL: 0.24,
  WARP_SPEED_REDUCED: 0.10,
  METEOR_PROB: 0.001,
  METEOR_MAX: 1,
  TWINKLE_PROB: 0.002,
  TWINKLE_DURATION: 800,
  TWINKLE_NEXT_MIN: 500,
  TWINKLE_NEXT_MAX: 1500,
  TWINKLE_ALPHA_MIN: 0.05,
  TWINKLE_ALPHA_MAX: 0.70,
  BASE_ALPHA_MIN: 0.15,
  BASE_ALPHA_MAX: 0.50,
  BASE_ALPHA_VARIANCE: 0.15,
};

// Camera constants
export const CAMERA = {
  ZOOM_NORMAL: 1.85,
  ZOOM_REDUCED: 1.35,
  RETURN_DELAY_MS: 180,
  INTERPOLATION_FACTOR: 0.12,
  ARRIVAL_THRESHOLD: 0.6,
  SCALE_THRESHOLD: 0.01,
};

// Ship constants
export const SHIP = {
  FLIGHT_MS_NORMAL: 900,
  FLIGHT_MS_REDUCED: 500,
  ARC_HEIGHT: 0.18,
  LAND_SCALE: 0.55,
  ANGLE_OFFSET: 0,
  TRAIL_DISTANCE: 34,
  TRAIL_BASE_SIZE_MIN: 10,
  TRAIL_BASE_SIZE_MAX: 17,
  TRAIL_LIFE_MIN: 0.45,
  TRAIL_LIFE_MAX: 0.90,
  TRAIL_VELOCITY_BASE: 80,
  TRAIL_VELOCITY_VARIANCE: 60,
  TRAIL_FADE_RATE: 8,
  TRAIL_INITIAL_ALPHA: 0.46,
  ENGINE_FLICKER_SPEED: 34,
  ENGINE_FLICKER_AMPLITUDE: 0.08,
  ENGINE_SCALE_SPEED: 18,
  ENGINE_SCALE_AMPLITUDE: 0.08,
  WOBBLE_X_SPEED: 1.3,
  WOBBLE_X_AMPLITUDE: 0.02,
  WOBBLE_Y_SPEED: 1.1,
  WOBBLE_Y_AMPLITUDE: 0.02,
  BANK_DECAY: 0.92,
  BANK_MULTIPLIER: 3.2,
  BANK_CLAMP: 0.5,
  BANK_INTERPOLATION: 0.15,
  TURN_VEL_INTERPOLATION: 0.5,
};

// Warp constants
export const WARP = {
  ENTER_FADE_MS_NORMAL: 450,
  ENTER_FADE_MS_REDUCED: 0,
  HOLD_MS_NORMAL: 1300,
  HOLD_MS_REDUCED: 200,
  EXIT_FADE_MS_NORMAL: 350,
  EXIT_FADE_MS_REDUCED: 0,
};

// Planet constants
export const PLANETS = {
  MIN_RADIUS: 36,
  MAX_RADIUS: 80,
  DEFAULT_RADIUS: 54,
  JITTER_AMPLITUDE_MIN: 1.2,
  JITTER_AMPLITUDE_MAX: 6,
  JITTER_SPEED: 0.001,
  SPARKLE_ALPHA_MIN: 0.25,
  SPARKLE_ALPHA_MAX: 0.35,
  SPARKLE_SPEED: 0.0006,
  SPARKLE_POSITION_FACTOR_X: 0.35,
  SPARKLE_POSITION_FACTOR_Y: 0.22,
  SPARKLE_RADIUS_FACTOR: 0.04,
  HALO_ALPHA: 0.16,
  HALO_PULSE_MIN: 0.88,
  HALO_PULSE_MAX: 1.0,
  HALO_PULSE_SPEED: 0.001,
  HALO_BLUR_MIN: 1.4,
  HALO_BLUR_MAX: 2.2,
  HALO_SCALE: 1.18,
  HOVER_ALPHA: 0.25,
  HOVER_SCALE: 1.15,
  RING_WIDTH_FACTOR: 0.12,
  RING_MIN_WIDTH: 2,
  LABEL_OFFSET_Y: 10,
  NAME_OFFSET_Y: 30,
};

// Asteroid belt constants
export const ASTEROIDS = {
  DEFAULT_COUNT: 120,
  DEFAULT_INNER: 1.6,
  DEFAULT_OUTER: 2.1,
  DEFAULT_TILT: -0.22,
  SIZE_MIN: 0.6,
  SIZE_MAX: 2.0,
  SHADE_MIN: 0.6,
  SHADE_MAX: 1.0,
  SPEED_MIN: 0.0006,
  SPEED_MAX: 0.0012,
  ALPHA_MULTIPLIER: 0.75,
  COLOR: 'rgba(220,230,255,0.85)',
  ELLIPSE_FACTOR: 0.52,
};

// UI constants
export const UI = {
  SHOW_CROSSHAIR: false,
  HOVER_RADIUS_BUFFER: 6,
  FLASH_SIZE: 40,
  FLASH_DURATION: 350,
  FLASH_SCALE_MAX: 2.6,
};

// Input constants
export const INPUT = {
  AUTOPILOT_IDLE_MS: Infinity,
  MOUSE_INTERPOLATION_FACTOR: 0.06,
  PARALLAX_FACTOR_IDLE: 0.00008,
  PARALLAX_FACTOR_MOVING: 0.0006,
  PARALLAX_MULTIPLIER: 40,
};

// Viewport constants
export const VIEWPORT = {
  DPR_MIN: 1,
  DPR_MAX: 3,
  DPR_CLAMP_SHIP: 2.5,
  RESIZE_THROTTLE_RAF: true,
  ORIENTATION_DELAY: 50,
};

// Station constants
export const STATION = {
  DEFAULT_RADIUS: 18,
  ROTATION_SPEED: 0.0035,
  PULSE_SPEED: 0.002,
  RING_ALPHA_MIN: 0.30,
  RING_ALPHA_MAX: 0.55,
  RING_SCALE: 1.9,
  RING_ELLIPSE_Y: 0.9,
  RING_ROTATION: -0.25,
  SPRITE_SCALE: 2.2,
  BLINK_SIZE: 1.6,
  BLINK_PULSE_AMPLITUDE: 0.8,
  LABEL_OFFSET_Y: 16,
};

// Color/Theme constants
export const THEMES = {
  CYAN: 'theme-cyan',
  VIOLET: 'theme-violet',
  MAGMA: 'theme-magma',
  EMERALD: 'theme-emerald',
};

export const THEME_TINTS = {
  [THEMES.CYAN]: [160, 210, 255],
  [THEMES.VIOLET]: [200, 170, 255],
  [THEMES.MAGMA]: [255, 170, 140],
  [THEMES.EMERALD]: [140, 255, 200],
  DEFAULT: [160, 210, 255],
};

// Timing constants
export const TIMING = {
  REQUEST_IDLE_CALLBACK_TIMEOUT: 1500,
  REQUEST_IDLE_CALLBACK_TIMEOUT_IMAGES: 2000,
  IMAGE_WARMUP_DELAY: 200,
  VISIBILITY_CHANGE_DELAY: 0,
};

// Easing constants
export const EASING = {
  CUBIC_BEZIER_FILL: 'cubic-bezier(.2,.7,.2,1)',
  FILL_DURATION: '1.1s',
  PANEL_IN_DURATION: '0.28s',
  PANEL_IN_EASE: 'ease-out',
};

